"""Add taxonomy_values and repo_taxonomy tables for embedding-based dynamic taxonomy

Revision ID: 013
Revises: 012
Create Date: 2026-03-24

Adds:
1. taxonomy_values — canonical taxonomy entries per dimension, with pgvector embedding
2. repo_taxonomy — raw values as generated by Claude, linked to taxonomy_values after normalization
"""
from typing import Sequence, Union

from alembic import op

revision: str = "013"
down_revision: Union[str, None] = "012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("""
        CREATE TABLE IF NOT EXISTS taxonomy_values (
            id SERIAL PRIMARY KEY,
            dimension TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            embedding_vec vector(384),
            repo_count INT DEFAULT 0,
            trending_score FLOAT DEFAULT 0,
            first_seen_at TIMESTAMPTZ DEFAULT NOW(),
            last_active_at TIMESTAMPTZ DEFAULT NOW(),
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_taxonomy_values_dim_name "
        "ON taxonomy_values (dimension, name)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_taxonomy_values_dimension "
        "ON taxonomy_values (dimension)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_taxonomy_values_embedding "
        "ON taxonomy_values USING hnsw (embedding_vec vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.execute("""
        CREATE TABLE IF NOT EXISTS repo_taxonomy (
            id SERIAL PRIMARY KEY,
            repo_id UUID NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
            dimension TEXT NOT NULL,
            raw_value TEXT NOT NULL,
            taxonomy_value_id INT REFERENCES taxonomy_values(id) ON DELETE SET NULL,
            similarity_score FLOAT,
            assigned_by TEXT DEFAULT 'enrichment',
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_repo_taxonomy_repo_id "
        "ON repo_taxonomy (repo_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_repo_taxonomy_dimension "
        "ON repo_taxonomy (dimension)"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_repo_taxonomy_repo_dim_val "
        "ON repo_taxonomy (repo_id, dimension, raw_value)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS repo_taxonomy")
    op.execute("DROP TABLE IF EXISTS taxonomy_values")
